雑文: scribble
Tips: tips
Unix系: unix
文字入力: input
GUI: GUI
Ruby: Ruby
Windows: Windows
生活: life
人間: human
計算機: computer
アルゴリズム: algorithm
本: livre
ブログ: blog
g91: g91
プログラミング: programming
ゲーム: game
ソフトウェア: software
日記: diary
科学: science
メール: email
twitter: twitter
ガシェット: gadget
Gentoo: Gentoo
インターネット: internet
軍事: military
